### ISSUE TITLE
Uglify fails to minify

### ISSUE THREAD

**Issue by gsantiago** [ytiurin/downscale#1]
I'm using create-react-app and it fails to generate the build with this module because Uglify does not support ES6 template strings.

![downscale](https://user-images.githubusercontent.com/4365542/33284852-90c585de-d397-11e7-8a1e-9b0068090eaa.png)

**Comment by ytiurin** [comment]
Will fix this soon. Thanks for pointing that out!

**Comment by ytiurin** [comment]
Fixed in version 1.0.3

**Comment by gsantiago** [comment]
@ytiurin Thank you very much!
